### ISSUE TITLE
Can I snag a part of your license?

### ISSUE THREAD

**Issue by jenstornell** [fabianmichael/kirby-imagekit#1]
I've done a boilerplate for the readme-file:
https://github.com/jenstornell/kirby-boiler-readme
## 1. I wonder if I could add a modified version of this text in it? For a better world, that is.

A part of your readme file is like this:

> However, even with a valid license code, it is discouraged to use it in any project, that promotes racism, sexism, homophobia, animal abuse or any other form of hate-speech.

Maybe my version would be:

> It is discouraged to use this plugin in any project, that promotes racism, sexism, homophobia, animal abuse or any other form of hate-speech.

**Can I use it in my boilerplate readme?**

I've still not tried your plugin, but hopefully I will have some time for it soon. But I have another question:
## 2. Where is the buy button?

Maybe I'm blind, but I could not find it. I will not buy it before I've tried it but when that is, it would be good to know where to go.

Thanks!

**Comment by fabianmichael** [comment]
> Can I use it in my boilerplate readme?

Of course, you’re welcome to use this snippet in your boiler readme! :-) I would like to see more of this in open source and also in commercial software. It is just a statement to make clear, that I don’t want my software to be used in something that is diametrally opposed to my attitudes. However, I would never include it directly into a license, because in some cases it is very hard to judge if something falls into one of the categories listed above. It is up to the user to decide, if he/she wants to use the plugin and I don’t claim to able to judge ever

> Where is the buy button?

I made them a little more visually appealing by replacing the links with buttons. Just read the readme, you should be able to find them.

**Comment by jenstornell** [comment]
I've added it now. Modified it a little and I added "violence" to it as well. Thanks!

https://github.com/jenstornell/kirby-boiler-readme
