### ISSUE TITLE
Idea: automatic thumbnail creation with hooks

### ISSUE THREAD

**Issue by jakobploens** [fabianmichael/kirby-imagekit#7]
Wouldn't this be possible? Maybe you already thought about that and there are pitfalls/disadvantages, but I absolutely see use cases where this could be handy (especially at bigger sites with many subpages/thumbnails). If not with hooks, this might be done with a per-page-creation-action, triggered by a button or sidebar widget (if they'll make it at some point ;)).

**Comment by fabianmichael** [comment]
He @jakobploens,

that’s in fact a great idea! Unfortunately, hooks won’t save us here, because they’re only executed on the server-side. I saw another plugin, that adds custom JS to the admin by using an output buffer (`ob_start()` etc.) to inject their script tag into the output, but this really feels like a hack to me. On the other hand, it should work pretty well without too much issues. After every save or upload, the page could trigger the ImageKit API via JS to pre-generate thumbnails in the background while the user is fiddling around with Kirbytext. As it does not cost much CPU time on the client, it should IMHO be done automatically, maybe just showing a subtle progress bar somewhere in the sidebar, informing the power users that thumbnails are being generated. However, this would only work in a reliable way after saving the page, because some thumbnails might depend on Kirbytext.

I will keep this issue open and definitely add this in some way, as soon as the corresponding APIs have landed in Kirby. Thanks for sharing your idea! :-D
